I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    $ config.keymap['dismiss'].remove('mousedown_1')
  File "game/script.rpy", line 26, in <module>
    $ config.keymap['dismiss'].remove('mousedown_1')
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 26, in script
    $ config.keymap['dismiss'].remove('mousedown_1')
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 26, in <module>
    $ config.keymap['dismiss'].remove('mousedown_1')
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "renpy/common/00keymap.rpy", line 28, in remove
    _list.remove(self, a)
    ~~~~~~~~~~~~^^^^^^^^^
ValueError: list.remove(x): x not in list

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.1.25072401
Still Heart 1.0
Mon Sep 29 01:40:18 2025
